apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mailhog-prod

resources:
- ../../base

namePrefix: prod-

commonLabels:
  environment: prod

patchesStrategicMerge:
- replica-patch.yaml

replicas:
- name: mailhog
  count: 2
